### ISSUE TITLE
[Bug]: rocBLAS error: Cannot read TensileLibrary.dat

### ISSUE THREAD

**Issue by CHEN-EIGAWA** [ROCmSoftwarePlatform/rocBLAS#1299]
### Describe the bug
I try to build ROCm environment with Pytorch2.0 but it seems here are some problem and I do not sure how to solve it.
It says that rocBLAS error: Cannot read /home/chen/.local/lib/python3.8/site-packages/torch/lib/rocblas/library/TensileLibrary.dat when I try to run an easy MNIST testing python program and I am sure that there is no error for coding style because I have test the program on Colab.

### To Reproduce
Precise version of rocBLAS installed or rocBLAS commit hash if building from source.
1. Install '...' version '...'
2. Run '...' with data '...'
3. See error on logfile '...'
I am sorry about that I do not sure how to check this part

### Expected behavior

In my debug result shows up that the problem when using sentence to propagate like:
result = model(torch.rand((batch_size, channel, height, width)).to(device))

whenever I propagate then this happens and crash.
I have read this article but I do not sure how to solve it.

This is in host environment and when I try on docker container using images pull from rocm I also met this problem.
this is newly build Ubuntu 20.04 LTS and I use these commend to install rocm:
wget https://repo.radeon.com/amdgpu-install/5.4/ubuntu/focal/amdgpu-install_5.4.50400-1_all.deb
sudo apt-get install ./amdgpu-install_5.4.50400-1_all.deb
sudo amdgpu-install --usecase=rocm,hip,mllib --no-dkms
sudo usermod -a -G video,render $LOGNAME

### Log-files
this are the log file when I try to debug through sentences by Jupyter on VScode
**
Visual Studio Code (1.76.1, undefined, desktop)
Jupyter Extension Version: 2023.3.1000771902.
Python Extension Version: 2023.4.1.
Workspace folder /home/chen/pytorch_works/AI_intro/Lab1
warn 14:52:38.018: Exception while attempting zmq : /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/out/node_modules/zeromq/prebuilds/linux-x64/node.napi.glibc.node)
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTestcf'
info 14:52:38.170: Attempting to start a server because of preload conditions ...
info 14:52:38.174: LSP Notebooks experiment is enabled
info 14:52:38.186: Checking for server existence.
warn 14:52:38.446: No interpreter with path /opt/conda/bin/python found in Python API, will convert Uri path to string as Id file:///opt/conda/bin/python
info 14:52:38.451: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]) for '/home/chen/pytorch_works/AI_intro/Lab1/Lab1_E24086195.ipynb' (disableUI=true)
warn 14:52:38.489: Failed to get activated env vars with python /bin/python3 in 39ms
info 14:52:38.510: Process Execution: > /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
> /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
error 14:52:38.527: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:38.531: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
warn 14:52:40.600: Failed to get activated env vars with python /bin/python3 in 36ms
error 14:52:40.602: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:40.609: Process Execution: > /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
warn 14:52:40.610: Failed to get activated env vars with python /bin/python3 in 46ms
error 14:52:40.611: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:40.617: Process Execution: > /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
warn 14:52:40.747: Failed to get activated env vars with python /bin/python3 in 3ms
error 14:52:40.748: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:40.753: Process Execution: > /bin/python3 -m jupyter kernelspec --version
> /bin/python3 -m jupyter kernelspec --version
info 14:52:41.060: Connecting to server
info 14:52:41.060: Launching server
info 14:52:41.060: Starting Notebook
warn 14:52:41.063: Failed to get activated env vars with python /bin/python3 in 4ms
error 14:52:41.064: Unable to determine site packages path for python /bin/python3 (Unknown)
warn 14:52:41.065: Failed to get activated env vars with python /bin/python3 in 6ms
error 14:52:41.066: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:41.067: Generating custom default config at /tmp/f352fa9c-234e-4a3e-b551-232088dc0b8d/jupyter_notebook_config.py
Starting Jupyter from /bin/python3 with arguments --no-browser --notebook-dir="/home/chen/pytorch_works/AI_intro/Lab1" --config=/tmp/f352fa9c-234e-4a3e-b551-232088dc0b8d/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
warn 14:52:41.075: Failed to get activated env vars with python /bin/python3 in 8ms
error 14:52:41.076: Unable to determine site packages path for python /bin/python3 (Unknown)
warn 14:52:41.084: Failed to get activated env vars with python /bin/python3 in 8ms
error 14:52:41.085: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:41.090: Process Execution: > /bin/python3 -m jupyter notebook --no-browser --notebook-dir="/home/chen/pytorch_works/AI_intro/Lab1" --config=/tmp/f352fa9c-234e-4a3e-b551-232088dc0b8d/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /bin/python3 -m jupyter notebook --no-browser --notebook-dir="/home/chen/pytorch_works/AI_intro/Lab1" --config=/tmp/f352fa9c-234e-4a3e-b551-232088dc0b8d/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
/home/chen/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/chen/pytorch_works/AI_intro/Lab1' instead of '"/home/chen/pytorch_works/AI_intro/Lab1"' if you require traitlets >=5.
  warn(
[I 14:52:42.178 NotebookApp] 启动notebooks 在本地路径: /home/chen/pytorch_works/AI_intro/Lab1
[I 14:52:42.178 NotebookApp] 本程序运行在: http://localhost:8888/?token=4c65840ed5701364d909990e729b344b598f1451958ff991
[I 14:52:42.178 NotebookApp]  or http://127.0.0.1:8888/?token=4c65840ed5701364d909990e729b344b598f1451958ff991
[I 14:52:42.178 NotebookApp] 使用control-c停止此服务器并关闭所有内核(两次跳过确认).
[C 14:52:42.180 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/chen/.local/share/jupyter/runtime/nbserver-5203-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=4c65840ed5701364d909990e729b344b598f1451958ff991
     or http://127.0.0.1:8888/?token=4c65840ed5701364d909990e729b344b598f1451958ff991
warn 14:52:42.208: Failed to get activated env vars with python /bin/python3 in 30ms
error 14:52:42.209: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:42.217: Process Execution: > /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/pythonFiles/vscode_datascience_helpers/getServerInfo.py
warn 14:52:42.218: Failed to get activated env vars with python /bin/python3 in 39ms
error 14:52:42.218: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:42.224: Process Execution: > /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/pythonFiles/vscode_datascience_helpers/getServerInfo.py
warn 14:52:42.226: Failed to get activated env vars with python /bin/python3 in 45ms
error 14:52:42.227: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:42.231: Process Execution: > /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 14:52:42.490: Connecting local server kernel http://localhost:8888/
info 14:52:42.490: Creating server with url : http://localhost:8888/
info 14:52:42.494: Server started.
[I 14:52:42.586 NotebookApp] Creating new notebook in 
/usr/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
info 14:52:42.637: installMissingDependencies /bin/python3, ui.disabled=true for resource '/home/chen/pytorch_works/AI_intro/Lab1/Lab1_E24086195.ipynb'
warn 14:52:42.646: Failed to get activated env vars with python /bin/python3 in 9ms
error 14:52:42.647: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:42.653: Process Execution: > /bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
warn 14:52:42.823: Failed to get activated env vars with python /bin/python3 in 45ms
error 14:52:42.824: Unable to determine site packages path for python /bin/python3 (Unknown)
[I 14:52:42.854 NotebookApp] Kernel started: c0d52012-4882-4e22-a0fa-7199ad20e5cf
[W 14:52:42.867 NotebookApp] delete /Lab1_E24086195-jvsc-f32aba47-c661-410e-9a19-55d65ac8d2c17664dcf5-7ce5-4efa-b677-8a761fb85ed5.ipynb
info 14:52:52.907: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
warn 14:52:53.012: Failed to get activated env vars with python /bin/python3 in 4ms
error 14:52:53.013: Unable to determine site packages path for python /bin/python3 (Unknown)
info 14:52:53.018: Process Execution: > /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/pythonFiles/printJupyterDataDir.py
> /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/pythonFiles/printJupyterDataDir.py
info 16:19:06.791: Dispose Kernel '/home/chen/pytorch_works/AI_intro/Lab1/Lab1_E24086195.ipynb' associated with '/home/chen/pytorch_works/AI_intro/Lab1/Lab1_E24086195.ipynb'
[I 16:19:06.857 NotebookApp] Kernel shutdown: c0d52012-4882-4e22-a0fa-7199ad20e5cf
info 16:31:24.389: Attempting to start a server because of preload conditions ...
info 16:31:24.491: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]) for '/home/chen/pytorch_works/AI_intro/Lab1/Lab1_E24086195.ipynb' (disableUI=true)
[I 16:31:24.508 NotebookApp] Creating new notebook in 
warn 16:31:24.510: Failed to get activated env vars with python /bin/python3 in 17ms
error 16:31:24.511: Unable to determine site packages path for python /bin/python3 (Unknown)
info 16:31:24.518: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
info 16:31:24.614: installMissingDependencies /bin/python3, ui.disabled=true for resource '/home/chen/pytorch_works/AI_intro/Lab1/Lab1_E24086195.ipynb'
warn 16:31:24.618: Failed to get activated env vars with python /bin/python3 in 3ms
error 16:31:24.619: Unable to determine site packages path for python /bin/python3 (Unknown)
info 16:31:24.624: Process Execution: > /bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
warn 16:31:24.876: Failed to get activated env vars with python /bin/python3 in 4ms
error 16:31:24.878: Unable to determine site packages path for python /bin/python3 (Unknown)
[I 16:31:24.941 NotebookApp] Kernel started: 3f6aecb1-f15d-4933-a03d-a6932dd6b04d
[W 16:31:24.970 NotebookApp] delete /Lab1_E24086195-jvsc-44c0f9b7-ad33-40e3-991d-234b6aa11e68007cce5e-b0bb-4297-a96d-bce66c69862a.ipynb
info 16:31:35.011: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
[I 16:32:24.941 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 3f6aecb1-f15d-4933-a03d-a6932dd6b04d restarted
error 16:32:24.956: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/out/extension.node.js:2:32419)
	at /home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/out/extension.node.js:2:26638
	at Map.forEach (<anonymous>)
	at v._clearKernelState (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/out/extension.node.js:2:26623)
	at /home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.3.1000771902/out/extension.node.js:2:29066
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 16:32:24.957: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 16:32:24.958: Cancel all remaining cells true || Error || undefined
[I 16:32:24.956 NotebookApp] Starting buffering for 3f6aecb1-f15d-4933-a03d-a6932dd6b04d:71808400-64c1-450b-9ec6-564451931de7
[I 16:32:24.963 NotebookApp] Restoring connection for 3f6aecb1-f15d-4933-a03d-a6932dd6b04d:71808400-64c1-450b-9ec6-564451931de7
info 17:08:23.079: Loading webview. View is notset
info 17:08:23.080: Loading web view...
info 17:08:23.081: Webview panel created.
**

### Environment

| Hardware | description |
|-----|-----|
| CPU | Ryzen5-3600 |
| GPU | RX-6700-XT |

The above hardware Table information can be generated by command:
```
rocminfo | grep Marketing
```

| Software | version |
|-----|-----|
| rocm-core | v5.4.0.50400-72~20.04 |
| rocblas | v2.46.0.50400-72~20.04 |

The above software Table information can be queried with:
```
Ubuntu/Debian:
dpkg -s rocm-core | grep Version
dpkg -s rocblas | grep Version
Centos/RHEL:
rpm -qa | grep rocm-core
rpm -qa | grep rocblas
SLES:
zypper se -s | grep rocm-core
zypper se -s | grep rocblas
```

Make sure that ROCm is correctly installed and to capture detailed environment information run the following command:
```
```
Linux Kernel
```
5.15.0-67-generic
```
rocm-smi
```
======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp (DieEdge)  AvgPwr  SCLK    MCLK     Fan     Perf  PwrCap  VRAM%  GPU%  
0    54.0c           36.0W   500Mhz  1000Mhz  32.55%  auto  203.0W    9%   0%    
================================================================================
============================= End of ROCm SMI Log ==============================
```
hipconfig
```
HIP version  : 5.4.22801-aaa1e3d8

== hipconfig
HIP_PATH     : /opt/rocm-5.4.0
ROCM_PATH    : /opt/rocm-5.4.0
HIP_COMPILER : clang
HIP_PLATFORM : amd
HIP_RUNTIME  : rocclr
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I/opt/rocm-5.4.0/include -I/opt/rocm-5.4.0/llvm/bin/../lib/clang/15.0.0 -I/opt/rocm-5.4.0/hsa/include

== hip-clang
HSA_PATH         : /opt/rocm-5.4.0/hsa
HIP_CLANG_PATH   : /opt/rocm-5.4.0/llvm/bin
AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.4.0 22465 d6f0fe8b22e3d8ce0f2cbd657ea14b16043018a5)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.4.0/llvm/bin
AMD LLVM version 15.0.0git
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver2

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
hip-clang-cxxflags :  -isystem "/opt/rocm-5.4.0/llvm/lib/clang/15.0.0/include/.." -isystem /opt/rocm-5.4.0/hsa/include -isystem "/opt/rocm-5.4.0/include" -O3
hip-clang-ldflags  :  -L"/opt/rocm-5.4.0/lib" -O3 -lgcc_s -lgcc -lpthread -lm -lrt

=== Environment Variables
PATH=/home/chen/.local/bin:/home/chen/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

== Linux Kernel
Hostname     : chen-desktop
Linux chen-desktop 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```
rocminfo
```
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 5 3600 6-Core Processor  
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 5 3600 6-Core Processor  
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3600                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            12                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    16306956(0xf8d30c) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    16306956(0xf8d30c) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16306956(0xf8d30c) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1031                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon RX 6700 XT              
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      3072(0xc00) KB                     
    L3:                      98304(0x18000) KB                  
  Chip ID:                 29663(0x73df)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2855                               
  BDFID:                   3328                               
  Internal Node ID:        1                                  
  Compute Unit:            40                                 
  SIMDs per CU:            2                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    12566528(0xbfc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1031         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***
```
lspci | grep -i vga
```
0d:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 73df (rev c1)
Attach `environment.txt`

**Comment by cgmb** [comment]
Thanks for the all the detail you included in the bug report. It made it very easy to see the problem.

The official binaries provided by AMD are not built for gfx1031. It is not an officially supported architecture. However, you can set the environment variable `HSA_OVERRIDE_GFX_VERSION=10.3.0` to force libhsakmt to report your GPU as being gfx1030. The gfx1031 instruction set and the gfx1030 instruction set are identical, so it should allow binaries built for gfx1030 to run on your machine.

As for what could be done in rocBLAS / Tensile to prevent future bug reports, I think there's probably two things:

1. The error message that Tensile prints for this situation is very misleading and it should be improved.
2. Tensile should be updated to load any compatible code objects for a given processor (SWDEV-347481).

**Comment by CHEN-EIGAWA** [comment]
I really appreciate to your helping hand and the command really works while this problem troubles me about a week, now I can run training program with RX6700XT and it really works with using command ```python3 main.py``` after adding environment variable ```HSA_OVERRIDE_GFX_VERSION=10.3.0```. 

But there is still a problem, when I try to run jupyter ```ipynb``` on Vscode, the problem still appear. Does this mean I need to uninstall and install jupyter or VScode jupyter extension after that again?

**Comment by CHEN-EIGAWA** [comment]
I will provide the jupyter log for dead kernel, I do not sure if this is happened because of jupyter, torch or ROCm
```
Visual Studio Code (1.76.1, undefined, desktop)
Jupyter Extension Version: 2023.2.1200692131.
Python Extension Version: 2023.4.1.
Workspace folder /home/chen/pytorch_works/AI_intro/Lab1
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTestcf'
info 12:48:03.680: LSP Notebooks experiment is enabled
warn 12:48:03.771: Failed to get activated env vars with python /bin/python3 in 51ms
info 12:48:03.775: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]) for '/home/chen/pytorch_works/AI_intro/Lab1/Lab1_E24086195.ipynb' (disableUI=true)
info 12:48:03.785: Process Execution: > /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
> /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
info 12:48:03.814: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
warn 12:48:03.825: Failed to get activated env vars with python /bin/python3 in 31ms
info 12:48:03.836: Process Execution: > /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
warn 12:48:03.852: Failed to get activated env vars with python /bin/python3 in 12ms
warn 12:48:03.854: Failed to get activated env vars with python /bin/python3 in 13ms
info 12:48:03.863: Process Execution: > /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"aa8f7d08-2d19-498a-8e4a-ad0958a122db" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/chen/.local/share/jupyter/runtime/kernel-v2-13267im2SJyVEMo2D.json
> /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"aa8f7d08-2d19-498a-8e4a-ad0958a122db" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/chen/.local/share/jupyter/runtime/kernel-v2-13267im2SJyVEMo2D.json
info 12:48:03.863: Process Execution: cwd: ~/pytorch_works/AI_intro/Lab1
cwd: ~/pytorch_works/AI_intro/Lab1
info 12:48:03.971: ipykernel version & path 6.21.3, /usr/local/lib/python3.8/dist-packages/ipykernel/__init__.py for /bin/python3
info 12:48:04.291: Started Kernel Python 3.8.10 (pid: 13722)
warn 12:48:08.013: Failed to get activated env vars with python /bin/python3 in 66ms
info 12:48:08.024: Process Execution: > /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/printJupyterDataDir.py
> /bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/printJupyterDataDir.py
error 12:48:34.399: Disposing session as kernel process died ExitCode: undefined, Reason: /home/chen/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/home/chen/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'aa8f7d08-2d19-498a-8e4a-ad0958a122db' instead of 'b"aa8f7d08-2d19-498a-8e4a-ad0958a122db"'.
  warn(

info 12:48:34.400: Dispose Kernel process 13722.
error 12:48:34.401: Raw kernel process exited code: undefined
error 12:48:34.404: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:33213)
	at /home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:52265
	at Map.forEach (<anonymous>)
	at y._clearKernelState (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:52250)
	at y.dispose (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:45732)
	at /home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:127079
	at ee (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:2:1552543)
	at dh.dispose (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:127055)
	at hh.dispose (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:17:134354)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 12:48:34.405: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 12:48:34.407: Cancel all remaining cells true || Error || undefined
error 12:48:43.853: Error in execution [jf [Error]: The kernel 'Python 3.8.10' died. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
	at Lv.verifyKernelState (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:24:151174)
	at async Kv.executeCell (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:24:161389)
	at async Promise.all (index 0)
	at async Kv.handleExecution (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:24:158306)] {
  category: 'unknown',
  originalException: undefined,
  kernelConnectionMetadata: ea {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/temp/jupyter/kernels/pythonjvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1/kernel.json',
      interpreterPath: '/bin/python3',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'Python 3',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/bin/python3',
      sysPrefix: '/usr',
      displayPath: [f],
      envName: '',
      displayName: '',
      envType: 'Unknown',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher'
  }
}
error 12:48:43.854: Error in execution (get message for cell) [jf [Error]: The kernel 'Python 3.8.10' died. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
	at Lv.verifyKernelState (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:24:151174)
	at async Kv.executeCell (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:24:161389)
	at async Promise.all (index 0)
	at async Kv.handleExecution (/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/extension.node.js:24:158306)] {
  category: 'unknown',
  originalException: undefined,
  kernelConnectionMetadata: ea {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/chen/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/temp/jupyter/kernels/pythonjvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1/kernel.json',
      interpreterPath: '/bin/python3',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'Python 3',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/bin/python3',
      sysPrefix: '/usr',
      displayPath: [f],
      envName: '',
      displayName: '',
      envType: 'Unknown',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher'
  }
}
```

**Comment by cgmb** [comment]
Unfortunately, I'm not familiar with Jupyter and I don't see any mention of ROCm in the logs. You'll have to narrow the problem down to something within ROCm before I can do much to help.

**Comment by CHEN-EIGAWA** [comment]
**I solve that problem today**, I found that Jupyter did not receive the environment variable `HSA_OVERRIDE_GFX_VERSION=10.3.0` though I export the vaiable in terminal of VScode. I found this when I call environment variables in VScode terminal, I did not see`HSA_OVERRIDE_GFX_VERSION=10.3.0` .  
Today I decided to export the environment variable into profile `/etc/environment` instead of running . Then I solved the problem that when Jupyter runs propagating then it crashes.  
Thanks to your precise problem pointing out and fixing. My problem is so far all finished.  

**I do not sure if there will be any problem if I do not do the fixing you mention before. You said that:**
>As for what could be done in rocBLAS / Tensile to prevent future bug reports, I think there's probably two things:
>1. The error message that Tensile prints for this situation is very misleading and it should be improved.
>2. Tensile should be updated to load any compatible code objects for a given processor (SWDEV-347481).

**How can I do to fix the problem you mention, or is it okay to be like that?**
